import json

from adas_cc.generators.render import (
    render_claude_md,
    render_command,
    render_format_hook_script,
    render_settings_json,
    render_skill,
    render_subagent,
)


def test_render_subagent_includes_frontmatter_and_handoff():
    agent = {
        "name": "planner",
        "description": "Plan tasks. Use proactively.",
        "tools": ["Read", "Grep", "Glob"],
        "model": "inherit",
        "system_prompt": "You are a planner.\n\nDo the planning thing.",
        "handoff_to": ["implementer"],
        "color": "blue",
    }
    out = render_subagent(agent)

    assert out.startswith("---\n")
    assert "name: planner" in out
    assert "description: Plan tasks. Use proactively." in out
    assert "tools: Read, Grep, Glob" in out
    assert "model: inherit" in out
    assert "color: blue" in out
    assert "You are a planner." in out
    assert "hand off to: `implementer`" in out


def test_render_subagent_omits_empty_optional_fields():
    agent = {
        "name": "tester",
        "description": "Runs tests.",
        "tools": [],
        "model": "",
        "system_prompt": "You test things.",
        "handoff_to": [],
        "color": None,
    }
    out = render_subagent(agent)

    assert "tools:" not in out
    assert "model:" not in out
    assert "color:" not in out
    assert "hand off to" not in out


def test_render_command_with_and_without_optional_fields():
    cmd = {
        "name": "plan",
        "description": "Plan a task",
        "argument_hint": "[task]",
        "allowed_tools": ["Read", "Grep"],
        "body": "Use the planner subagent for: $ARGUMENTS",
    }
    out = render_command(cmd)
    assert "description: Plan a task" in out
    assert "argument-hint: [task]" in out
    assert "allowed-tools: Read, Grep" in out
    assert "$ARGUMENTS" in out

    minimal = {"name": "noop", "description": "Does nothing", "body": "Do nothing."}
    out2 = render_command(minimal)
    assert "argument-hint" not in out2
    assert "allowed-tools" not in out2


def test_render_skill_frontmatter_only_has_spec_fields():
    skill = {"name": "run-tests", "description": "Run the suite.", "body": "1. run pytest"}
    out = render_skill(skill)
    assert out.startswith("---\nname: run-tests\ndescription: Run the suite.\n---\n")
    assert "1. run pytest" in out


def test_render_settings_json_merges_into_existing_non_hook_keys():
    existing = {"permissions": {"deny": ["Agent(Explore)"]}}
    hooks = [
        {
            "event": "PostToolUse",
            "matcher": "Edit|Write",
            "command": ".claude/hooks/format-changed-file.sh",
            "description": "fmt",
        }
    ]
    out = json.loads(render_settings_json(existing, hooks))

    assert out["permissions"] == {"deny": ["Agent(Explore)"]}
    assert out["hooks"]["PostToolUse"][0]["matcher"] == "Edit|Write"
    assert out["hooks"]["PostToolUse"][0]["hooks"][0]["type"] == "command"
    assert out["hooks"]["PostToolUse"][0]["hooks"][0]["command"] == ".claude/hooks/format-changed-file.sh"


def test_render_settings_json_appends_to_existing_hooks_for_same_event():
    existing = {
        "hooks": {
            "PostToolUse": [
                {"matcher": "Bash", "hooks": [{"type": "command", "command": "./scripts/audit.sh"}]}
            ]
        }
    }
    hooks = [
        {"event": "PostToolUse", "matcher": "Edit|Write", "command": ".claude/hooks/fmt.sh", "description": "fmt"}
    ]
    out = json.loads(render_settings_json(existing, hooks))
    matchers = [entry["matcher"] for entry in out["hooks"]["PostToolUse"]]
    assert matchers == ["Bash", "Edit|Write"]


def test_render_format_hook_script_dispatches_by_extension():
    script = render_format_hook_script("python")
    assert script.startswith("#!/bin/bash")
    assert "*.py)" in script
    assert "ruff format" in script
    assert "*.go)" in script and "gofmt" in script


def test_render_claude_md_wraps_summary_and_body():
    out = render_claude_md("A test project.", "  ## Stack\npython\n  ")
    assert out.startswith("<!-- Generated by ADAS-CC")
    assert "# A test project." in out
    assert "## Stack\npython" in out
