"""Pure rendering functions: DesignSpec pieces -> file contents (strings).

Kept free of any I/O so they're trivial to unit test. `nodes/generator.py`
handles turning these into `ProposedFile` entries with real paths and
new-vs-diff status.
"""
from __future__ import annotations

import json

from adas_cc.state import CommandSpec, HookSpec, SkillSpec, SubagentSpec


def render_claude_md(project_summary: str, body: str) -> str:
    return (
        "<!-- Generated by ADAS-CC. Edit freely; regenerate with `adas-cc scan` -->\n\n"
        f"# {project_summary}\n\n{body.strip()}\n"
    )


def render_subagent(agent: SubagentSpec) -> str:
    frontmatter = {
        "name": agent["name"],
        "description": agent["description"],
    }
    if agent.get("tools"):
        frontmatter["tools"] = ", ".join(agent["tools"])
    if agent.get("model") and agent["model"] != "inherit":
        frontmatter["model"] = agent["model"]
    elif agent.get("model") == "inherit":
        frontmatter["model"] = "inherit"
    if agent.get("color"):
        frontmatter["color"] = agent["color"]

    lines = ["---"]
    for key, value in frontmatter.items():
        lines.append(f"{key}: {value}")
    lines.append("---")
    lines.append("")
    lines.append(agent["system_prompt"].strip())

    handoffs = agent.get("handoff_to") or []
    if handoffs:
        lines.append("")
        lines.append(
            "When you finish, suggest the user hand off to: "
            + ", ".join(f"`{h}`" for h in handoffs)
            + "."
        )
    lines.append("")
    return "\n".join(lines)


def render_command(cmd: CommandSpec) -> str:
    lines = ["---", f"description: {cmd['description']}"]
    if cmd.get("argument_hint"):
        lines.append(f"argument-hint: {cmd['argument_hint']}")
    if cmd.get("allowed_tools"):
        lines.append("allowed-tools: " + ", ".join(cmd["allowed_tools"]))
    lines.append("---")
    lines.append("")
    lines.append(cmd["body"].strip())
    lines.append("")
    return "\n".join(lines)


def render_skill(skill: SkillSpec) -> str:
    return (
        "---\n"
        f"name: {skill['name']}\n"
        f"description: {skill['description']}\n"
        "---\n\n"
        f"{skill['body'].strip()}\n"
    )


def render_settings_json(existing: dict | None, hooks: list[HookSpec]) -> str:
    """Merge hook specs into a settings.json `hooks` block.

    `existing` is the parsed contents of an existing `.claude/settings.json`
    (or None). Any non-hooks keys are preserved untouched.
    """
    settings = dict(existing) if existing else {}
    hooks_block: dict[str, list[dict]] = dict(settings.get("hooks", {}))

    by_event: dict[str, list[HookSpec]] = {}
    for h in hooks:
        by_event.setdefault(h["event"], []).append(h)

    for event, specs in by_event.items():
        entries = hooks_block.setdefault(event, [])
        for spec in specs:
            entries.append(
                {
                    "matcher": spec["matcher"],
                    "hooks": [{"type": "command", "command": spec["command"]}],
                }
            )

    settings["hooks"] = hooks_block
    return json.dumps(settings, indent=2) + "\n"


def render_format_hook_script(primary_language: str) -> str:
    """A minimal, dependency-checked formatter dispatched by a PostToolUse hook.

    Reads the hook JSON payload from stdin, extracts the edited file path,
    and runs a best-effort formatter for its extension. Silently no-ops for
    unknown extensions or missing formatters so it never blocks a session.
    """
    return f"""#!/bin/bash
# Generated by ADAS-CC. Best-effort formatter for {primary_language or 'this project'}.
# Wired up as a PostToolUse hook on Edit|Write in .claude/settings.json.
set -euo pipefail

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('tool_input',{{}}).get('file_path',''))" 2>/dev/null || true)

[ -z "$FILE_PATH" ] && exit 0
[ ! -f "$FILE_PATH" ] && exit 0

case "$FILE_PATH" in
  *.py)
    command -v ruff >/dev/null 2>&1 && ruff format "$FILE_PATH" >/dev/null 2>&1 || true
    ;;
  *.ts|*.tsx|*.js|*.jsx|*.json|*.css|*.md)
    command -v prettier >/dev/null 2>&1 && npx --no-install prettier --write "$FILE_PATH" >/dev/null 2>&1 || true
    ;;
  *.go)
    command -v gofmt >/dev/null 2>&1 && gofmt -w "$FILE_PATH" || true
    ;;
  *.rs)
    command -v rustfmt >/dev/null 2>&1 && rustfmt "$FILE_PATH" || true
    ;;
esac

exit 0
"""
